# Generated by Django 3.0 on 2019-12-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='money',
            field=models.IntegerField(default=10, verbose_name='余额'),
        ),
    ]
