# Generated by Django 2.1 on 2019-12-19 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app6', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
    ]
